FROM python:3.12-slim

ARG APP_VERSION
ENV APP_VERSION=${APP_VERSION}

WORKDIR /usr/src/app

COPY hello_world.py .

RUN pip install --no-cache-dir flask prometheus_client

EXPOSE 9000

CMD [ "python", "hello_world.py" ]


